import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,scryptSync} from 'node:crypto';
import {database} from '../lib/db';
import {importFiles,loadData,processPeriod,saveRule,saveCompany} from '../lib/store';
import {decrypt,hash,login,logout,requireAuth,checkOrigin,encrypt} from '../lib/security';
const header='CFOP;Valor Contábil;Base de Cálculo;Imposto Creditado;Isentas ou Não tributadas;Outras';
test('persistência, importação atômica, histórico, isolamento por competência e autenticação',async()=>{
 process.env.LOCAL_DATABASE_PATH='.data/test-'+randomUUID();delete process.env.DATABASE_URL;
 process.env.ALLOW_LOCAL_DATABASE='true';
 process.env.DATA_ENCRYPTION_KEY='a'.repeat(64);
 process.env.ADMIN_EMAIL='teste@local.test';
 process.env.ADMIN_PASSWORD_HASH='test-salt:'+scryptSync('senha-de-teste-segura','test-salt',64).toString('hex');
 process.env.APP_ORIGIN='http://127.0.0.1:3000';
 const line='1102;1000,00;1000,00;120,00;0,00;0,00';
 const item=(companyId='01',text=header+'\n'+line)=>({file:new File([text],companyId+'_ApuIcms.txt'),companyId,period:'2026-08',taxMode:'confirmar' as const,emptyConfirmed:false,replace:false});
 assert.throws(()=>checkOrigin(new Request('http://127.0.0.1:3000',{headers:{origin:'https://untrusted.example'}})),/não autorizada/);
 const db=await database();
 const [created]=await importFiles([item()],'teste');
 const [duplicate]=await importFiles([item()],'teste');assert.equal(created.id,duplicate.id);
 await assert.rejects(()=>importFiles([item('02'),item('03',header+'\nINVÁLIDO')],'teste'));
 assert.equal((await loadData('2026-08')).imports.length,1);
 await assert.rejects(()=>importFiles([item('04',header)],'teste'),/ausência de movimento/);
 await importFiles([{...item('04',header),emptyConfirmed:true}],'teste');
 await assert.rejects(()=>importFiles([item('02'),item('02')],'teste'),/mais de um arquivo/);
 const [stored]=await db.query<{source:string}>('SELECT source FROM mega_imports WHERE id=$1',[created.id]);
 assert.equal(decrypt(stored.source).toString(),header+'\n'+line);assert.notEqual(stored.source,header+'\n'+line);assert.equal(hash(decrypt(stored.source)),created.hash);
 const encrypted=encrypt(Buffer.from('segredo'));const damaged=Buffer.from(encrypted,'base64');damaged[15]^=1;assert.throws(()=>decrypt(damaged.toString('base64')));
 const first=await processPeriod('2026-08','teste');assert.equal(first.entries[0].category,'revisar');assert.equal(first.alerts.filter(a=>a.kind==='cobertura').length,4);
 await saveRule({cfop:'1102',companyId:'',uf:'',start:'2026-01',end:'',category:'tributada',operation:'compra',credit:'permitir',expectCredit:true,reason:'Regra fictícia exclusiva do banco de testes.',reference:'Referência do teste',active:true},'teste');
 const stale=await loadData('2026-08');assert.equal(stale.stale,true);assert.equal(stale.snapshot!.entries[0].category,'revisar');
 const second=await processPeriod('2026-08','teste');assert.equal(second.entries[0].category,'tributada');assert.equal(first.entries[0].category,'revisar');assert.notEqual(first.id,second.id);
 assert.equal((await loadData('2026-07')).snapshot,null);
 await importFiles([{...item(),period:'2026-07'}],'teste');assert.equal((await loadData('2026-08')).imports.length,2);assert.equal((await loadData('2026-07')).imports.length,1);
 await assert.rejects(()=>importFiles([item('01',header+'\n'+line.replace('1000,00','2000,00'))],'teste'),/Já há importação/);
 await importFiles([{...item('01',header+'\n'+line.replace('1000,00','2000,00')),replace:true}],'teste');
 assert.equal((await loadData('2026-08')).stale,true);
 const versions=await db.query('SELECT id FROM mega_imports WHERE company_id=$1 AND period=$2',['01','2026-08']);assert.equal(versions.length,2);
 await saveCompany({id:'01',name:'Matriz de teste',uf:'SP',cnpj:''},'teste');assert.equal((await loadData('2026-08')).companies[0].uf,'SP');
 const session=await login('teste@local.test','senha-de-teste-segura');assert.equal(session.status,200);
 const req=new Request('http://127.0.0.1:3000',{headers:{cookie:'mega_session='+session.token}});
 assert.equal(await requireAuth(req),'teste@local.test');
 await logout(req);await assert.rejects(()=>requireAuth(req),/Sessão expirada/);
 for(let i=0;i<5;i++)assert.equal((await login('teste@local.test','incorreta')).status,401);
 assert.equal((await login('teste@local.test','senha-de-teste-segura')).status,429);
 await db.close();
});
