'use client';
import {useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,ArrowRight,ArrowLeftRight,BarChart3,CheckCheck,ChevronRight,CircleHelp,FileCheck2,FileText,Search,ShieldCheck,Sparkles,TriangleAlert} from 'lucide-react';
import {totals} from '@/lib/audit';
import {categoryLabels,compact,money,percent,periodLabel} from '@/lib/format';
import type {Category} from '@/lib/types';
import {AlertList,Badge,colors,Empty,EntryTable,Kpi,type ViewProps} from './ui';
function select(p:ViewProps){const entries=(p.data.snapshot?.entries||[]).filter(e=>p.company==='all'||e.companyId===p.company);const alerts=(p.data.snapshot?.alerts||[]).filter(a=>p.company==='all'||a.companyId===p.company);return {entries,alerts,t:totals(entries)};}
export function Dashboard(p:ViewProps){
 const {entries,alerts,t}=select(p),[search,setSearch]=useState(''),[direction,setDirection]=useState('all'),[category,setCategory]=useState('all');
 const high=alerts.filter(a=>a.priority==='alta').length;
 const composition=entries.filter(e=>direction==='all'||e.direction===direction);
 const volume=composition.reduce((s,e)=>s+e.amount,0);
 const canChart=volume>0&&!composition.some(e=>e.amount<0);
 const categories=(Object.keys(categoryLabels) as Category[]).map(id=>({id,label:categoryLabels[id],value:composition.filter(e=>e.category===id).reduce((s,e)=>s+e.amount,0)}));
 let start=0;const gradient=categories.map(c=>{const end=start+(volume>0?Math.max(0,c.value)/volume*100:0);const str=colors[c.id]+' '+start+'% '+end+'%';start=end;return str;}).join(',');
 const filtered=entries.filter(e=>(category==='all'||e.category===category)&&(!search||(e.cfop+' '+p.data.companies.find(c=>c.id===e.companyId)?.name).toLowerCase().includes(search.toLowerCase())));
 return <><section className="period-brief"><div className="brief-icon"><Sparkles size={22}/></div><div className="brief-copy"><div className="brief-title">O que importa em {periodLabel(p.period)} <span>RESUMO AUTOMÁTICO</span></div><p>{high>0?<><b>{high} pontos de alta prioridade</b> precisam de atenção. </>:'Não há alertas de alta prioridade neste filtro. '}{alerts.length} alertas para revisão. {t.review>0?<>{money(t.review)} em movimentos permanecem sem classificação conclusiva.</>:'As classificações refletem os critérios cadastrados.'}{p.data.imports.length<6?' A cobertura do grupo está incompleta.':''}</p></div><button onClick={()=>p.onPage('audit')} className="brief-link">Abrir auditoria <ArrowRight size={17}/></button></section>
 <div className="kpi-grid"><Kpi title="Total de entradas" value={compact(t.incoming)} caption={'Compras classificadas: '+compact(t.purchases)} icon={ArrowDownLeft}/><Kpi title="Total de saídas" value={compact(t.outgoing)} caption={'Vendas classificadas: '+compact(t.sales)} icon={ArrowUpRight}/><Kpi title="ICMS crédito" value={compact(t.credit)} caption="Informado na origem · sujeito à revisão" icon={FileCheck2}/><Kpi title="ICMS débito" value={t.complete?compact(t.debit):'A confirmar'} caption={t.complete?'Coluna de saída confirmada':'Confirme o mapeamento das saídas'} icon={FileText}/><Kpi title="Saldo dos relatórios" value={t.complete?compact(t.balance):'Pendente'} caption="Débitos − créditos · sem ajustes" icon={BarChart3} accent/></div>
 <div className="dashboard-grid"><section className="panel composition"><div className="panel-heading"><div><h2>Composição das operações</h2><p>Valor e participação por regra cadastrada</p></div><select aria-label="Direção das operações" value={direction} onChange={e=>setDirection(e.target.value)}><option value="all">Entradas + saídas</option><option value="entrada">Entradas</option><option value="saida">Saídas</option></select></div><div className="composition-body"><div className="donut" style={{background:canChart?'conic-gradient('+gradient+')':'#edf0f3'}}><div><small>Volume total</small><strong>{compact(volume)}</strong><span>{composition.length} linhas de origem</span></div></div><div className="legend">{categories.map(c=><button key={c.id} onClick={()=>setCategory(category===c.id?'all':c.id)}><span className="category-dot" style={{background:colors[c.id]}}/><span>{c.label}</span><b>{compact(c.value)}</b><small>{canChart?percent(c.value,volume):'—'}</small></button>)}</div></div><div className="panel-note"><CircleHelp size={14}/>{composition.some(e=>e.amount<0)?'Há estornos na origem. Percentuais suspensos para evitar uma distribuição enganosa.':'Classificação por regra, sem presumir ST ou valor tributado pela base.'}</div></section>
 <section className="panel priorities"><div className="panel-heading"><div><h2>Foco da auditoria</h2><p>Comece pelos pontos de maior atenção</p></div><ShieldCheck size={21}/></div><div className="priority-total"><strong>{alerts.length}</strong><span>alertas<br/>no período</span><Badge tone="red">{high} alta prioridade</Badge></div>{[{label:'Créditos de ICMS',value:alerts.filter(a=>a.kind.startsWith('credito')).length,page:'credits' as const,color:'#d2775b'},{label:'CFOPs e critérios',value:alerts.filter(a=>['regra','criterio'].includes(a.kind)).length,page:'rules' as const,color:'#d3ac59'},{label:'Transferências',value:alerts.filter(a=>a.kind==='transferencia').length,page:'transfers' as const,color:'#6896aa'}].map(a=><button className="focus-row" key={a.label} onClick={()=>p.onPage(a.page)}><span className="category-dot" style={{background:a.color}}/><span>{a.label}</span><b>{a.value}</b><ChevronRight size={16}/></button>)}<button className="panel-action" onClick={()=>p.onPage('audit')}>Ver todos os alertas <ArrowRight size={16}/></button></section></div>
 <section className="panel"><div className="panel-heading"><div><h2>Análise por CFOP</h2><p>Rastreie cada valor até a linha original.</p></div><div className="table-controls">{category!=='all'&&<button className="button secondary" onClick={()=>setCategory('all')}>{categoryLabels[category as Category]} ×</button>}<div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar CFOP ou empresa" aria-label="Buscar lançamentos"/></div></div></div><EntryTable data={p.data} entries={filtered} onEntry={p.onEntry} limit={8}/><div className="panel-footer"><span>Valores brutos; entradas e saídas incluem transferências e outras operações.</span><button className="button text-button" onClick={()=>p.onPage('audit')}>Explorar lançamentos <ArrowRight size={15}/></button></div></section></>;
}
export function AuditView(p:ViewProps & {credits?:boolean}){
 const {entries,alerts,t}=select(p),[search,setSearch]=useState(''),[priority,setPriority]=useState('all');
 const filtered=alerts.filter(a=>(!p.credits||a.kind.startsWith('credito'))&&(priority==='all'||a.priority===priority)&&(!search||(a.title+' '+a.reason).toLowerCase().includes(search.toLowerCase())));
 const [entrySearch,setEntrySearch]=useState('');
 return <>{p.credits&&<div className="stats-three"><Kpi title="Crédito informado" value={money(t.credit)} caption="Entradas · antes da revisão fiscal" icon={FileCheck2}/><Kpi title="Possíveis créditos indevidos" value={String(alerts.filter(a=>a.kind==='credito-indevido').length)} caption="Ocorrências com vedação cadastrada" icon={TriangleAlert}/><Kpi title="Possíveis créditos não aproveitados" value={String(alerts.filter(a=>a.kind==='credito-ausente').length)} caption="Sem estimar alíquota ou crédito" icon={Search}/></div>}<section className="panel"><div className="panel-heading"><div><h2>{p.credits?'Auditoria de créditos':'Alertas do período'} <Badge tone="amber">{filtered.length}</Badge></h2><p>Indícios para revisão, com critérios e evidências.</p></div><div className="table-controls"><div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar alerta" aria-label="Buscar alerta"/></div><select aria-label="Prioridade" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Todas as prioridades</option><option value="alta">Alta prioridade</option><option value="media">Média prioridade</option><option value="baixa">Baixa prioridade</option></select></div></div><AlertList alerts={filtered} data={p.data} onEntry={p.onEntry}/></section><section className="panel"><div className="panel-heading"><div><h2>{p.credits?'Base de revisão dos créditos':'Todos os lançamentos'}</h2><p>Documento, valor, critério e linha de origem.</p></div><div className="search-field"><Search size={16}/><input value={entrySearch} onChange={e=>setEntrySearch(e.target.value)} placeholder="CFOP, chave ou documento" aria-label="Buscar lançamento"/></div></div><EntryTable entries={entries.filter(e=>(!p.credits||e.direction==='entrada')&&(!entrySearch||[e.cfop,e.key,e.document].join(' ').includes(entrySearch)))} data={p.data} onEntry={p.onEntry}/></section></>;
}
export function Transfers(p:ViewProps){
 const {entries}=select(p),transfers=(p.data.snapshot?.transfers||[]).filter(t=>t.entryIds.some(id=>entries.some(e=>e.id===id)));
 return <><div className="stats-three">{[{status:'Conferido',icon:CheckCheck,caption:'Chave, valores e contrapartes coincidem'},{status:'Revisar',icon:TriangleAlert,caption:'Ausência de chave ou divergência'},{status:'Não encontrado',icon:Search,caption:'Apenas um lado da NF-e disponível'}].map(v=><Kpi key={v.status} title={v.status} value={String(transfers.filter(t=>t.status===v.status).length)} caption={v.caption} icon={v.icon}/>)}</div><div className="notice"><CircleHelp size={19}/><span>Somente CFOPs marcados como transferência nas regras entram no cruzamento. Relatórios agregados não permitem confirmar uma NF-e.</span></div><section className="panel"><div className="panel-heading"><div><h2>Conciliação entre empresas</h2><p>Conferência documental; não conclui o tratamento tributário.</p></div><ArrowLeftRight size={21}/></div>{transfers.length?<div className="transfer-list">{transfers.map(t=><article key={t.id}><div className="transfer-top"><b>{t.key?'NF-e '+t.key:'Sem chave NF-e na origem'}</b><Badge tone={t.status==='Conferido'?'green':'amber'}>{t.status}</Badge></div><p>{t.reason}</p><div className="transfer-bottom"><strong>{money(t.amount)}</strong><div>{t.entryIds.map(id=>{const e=p.data.snapshot?.entries.find(e=>e.id===id);return e&&<button key={id} className="button secondary" onClick={()=>p.onEntry(e)}>{p.data.companies.find(c=>c.id===e.companyId)?.name} · {e.direction}<ChevronRight size={14}/></button>;})}</div></div></article>)}</div>:<Empty title="Nenhuma transferência identificada">Cadastre as regras dos CFOPs de transferência e processe novamente. Sem regra, não presumimos a natureza da operação.</Empty>}</section></>;
}
