'use client';
import {useEffect,useMemo,useState} from 'react';import {BookOpen,ChevronLeft,ChevronRight,Database,RefreshCw,Search,ShieldCheck} from 'lucide-react';
import {CFOP_GROUPS,CFOP_SOURCE,type CfopMasterRule} from '@/lib/cfop-master';import {DEFAULT_AUDIT_SETTINGS} from '@/lib/movement-audit';import {Badge,request,type ViewProps} from './ui';
type Catalog={total:number;versions:number;conditional:number;review:number;byGroup:Record<string,number>;rows:CfopMasterRule[];filtered:number;page:number};
export function CfopCatalog(p:ViewProps){const [catalog,setCatalog]=useState<Catalog|null>(null),[q,setQ]=useState(''),[group,setGroup]=useState('all'),[page,setPage]=useState(0),[detail,setDetail]=useState<CfopMasterRule|null>(null);
 useEffect(()=>{let active=true;if(!p.data.demo&&p.data.cfopInstalled)request('cfop-catalog?page='+page+'&q='+encodeURIComponent(q)+'&group='+group).then(v=>active&&setCatalog(v)).catch(()=>active&&setCatalog(null));return()=>{active=false}},[p.data.demo,p.data.cfopInstalled,page,q,group]);
 const settings=p.data.auditSettings||DEFAULT_AUDIT_SETTINGS,groups=useMemo(()=>catalog?Object.entries(catalog.byGroup).sort((a,b)=>b[1]-a[1]):[],[catalog]);
 async function install(){await p.perform(async()=>{const r=await request('cfop-install',{});await p.refresh();p.notify('Catálogo automático instalado: '+r.total+' CFOPs vigentes.');});}
 return <section className="panel motor-panel"><div className="panel-heading"><div><h2><BookOpen size={20}/>Catálogo mestre de CFOP</h2><p>Natureza e abrangência automáticas; tributação definida pelos dados do lançamento.</p></div>{!p.data.demo&&!p.data.cfopInstalled&&<button className="button primary" disabled={p.busy} onClick={install}><Database size={16}/>Instalar catálogo completo</button>} {!p.data.demo&&p.data.cfopInstalled&&<Badge tone="green">Instalado</Badge>}</div>
 <div className="notice"><ShieldCheck size={18}/><span><b>Fonte oficial:</b> Convênio s/nº de 15/12/1970, Anexo II, consolidação vigente. Versão conferida em {new Date(CFOP_SOURCE.checkedAt+'T12:00:00').toLocaleDateString('pt-BR')}. Nenhum CFOP concede crédito ou determina débito isoladamente.</span></div>
 {p.data.demo?<p className="catalog-empty">A demonstração não acessa o catálogo persistido do ambiente real.</p>:!catalog?<p className="catalog-empty">{p.data.cfopInstalled?'Carregando o catálogo…':'Clique em Instalar catálogo completo. As regras manuais existentes serão preservadas.'}</p>:<><div className="motor-stats"><div><strong>{catalog.total}</strong><span>CFOPs vigentes</span></div><div><strong>{catalog.conditional}</strong><span>condicionais</span></div><div><strong>{catalog.review}</strong><span>exigem parametrização</span></div></div><details className="motor-source"><summary>Quantidade por grupo</summary><div className="catalog-groups">{groups.map(([name,count])=><span key={name}>{name.replaceAll('_',' ')} <b>{count}</b></span>)}</div></details><div className="motor-filters"><label><span><Search size={15}/>Buscar CFOP ou descrição</span><input value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/></label><label><span>Grupo</span><select value={group} onChange={e=>{setGroup(e.target.value);setPage(0)}}><option value="all">Todos</option>{CFOP_GROUPS.map(g=><option key={g}>{g}</option>)}</select></label><label><span>Versão da fonte</span><input readOnly value={CFOP_SOURCE.version}/></label></div><div className="table-scroll"><table><thead><tr><th>CFOP</th><th>Descrição oficial</th><th>Grupo</th><th>Movimento</th><th>Crédito</th><th>Débito</th><th/></tr></thead><tbody>{catalog.rows.map(r=><tr key={r.id}><td><b>{r.cfop}</b><small>{r.ambito_operacao}</small></td><td>{r.descricao_oficial}</td><td><Badge>{r.grupo_cfop.replaceAll('_',' ')}</Badge></td><td>{r.tipo_movimento}</td><td>{r.permissao_credito_icms}</td><td>{r.gera_debito_icms}</td><td><button className="button text-button" onClick={()=>setDetail(r)}>Detalhar</button></td></tr>)}</tbody></table></div><div className="motor-pagination"><span>{catalog.filtered} resultado(s)</span><button className="button secondary" disabled={!page} onClick={()=>setPage(page-1)}><ChevronLeft size={15}/>Anterior</button><b>Página {page+1}</b><button className="button secondary" disabled={(page+1)*40>=catalog.filtered} onClick={()=>setPage(page+1)}>Próxima<ChevronRight size={15}/></button></div></>}
 {detail&&<div className="catalog-detail"><button className="icon-button" onClick={()=>setDetail(null)}>×</button><h3>CFOP {detail.cfop}</h3><p>{detail.descricao_oficial}</p><dl><dt>Grupo</dt><dd>{detail.grupo_cfop}</dd><dt>Natureza</dt><dd>{detail.natureza_operacao}</dd><dt>Abrangência</dt><dd>{detail.ambito_operacao}</dd><dt>Compras / faturamento</dt><dd>{detail.impacta_compras} / {detail.impacta_faturamento}</dd><dt>Crédito / débito</dt><dd>{detail.permissao_credito_icms} / {detail.gera_debito_icms}</dd><dt>Condições</dt><dd>{detail.motivo_condicoes}</dd><dt>Fundamento</dt><dd>{detail.fundamento_legal}</dd><dt>Vigência</dt><dd>{detail.vigencia_inicial} a {detail.vigencia_final||'vigente'}</dd></dl></div>}
 <details className="motor-source"><summary>Parâmetros de reconciliação</summary><p>Tolerância: {(settings.toleranceCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} e {settings.tolerancePercent.toLocaleString('pt-BR')}%. Crítico: {(settings.criticalCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} ou {settings.criticalPercent.toLocaleString('pt-BR')}%. Os dois limites de tolerância precisam ser atendidos; um limite crítico basta para elevar a prioridade.</p></details></section>;
}
