'use client';
import {useRef,useState} from 'react';
import {Building2,CircleHelp,Database,Download,FileText,Search,UploadCloud,ChevronRight} from 'lucide-react';
import type {TaxMode} from '@/lib/types';
import {Badge,Dialog,request,type ViewProps} from './ui';
type UploadRow={file:File;companyId:string;taxMode:TaxMode;emptyConfirmed:boolean;replace:boolean};
type Preview={filename:string;rows?:number;warnings?:string[];encoding?:string;error?:string};
export default function Imports({data,period,refresh,perform,notify,busy}:ViewProps){
 const [declaration,setDeclaration]=useState<{companyId:string;noMovement:boolean}|null>(null);const covered=new Set([...data.imports.map(i=>i.companyId),...(data.declarations||[]).map(d=>d.companyId)]).size;const [uploads,setUploads]=useState<UploadRow[]>([]),[previews,setPreviews]=useState<Preview[]>([]);const fileInput=useRef<HTMLInputElement>(null);
 function declared(companyId:string){return !!data.declarations?.some(d=>d.companyId===companyId&&d.period===period);} function choose(files:FileList|null){if(!files)return;setUploads(Array.from(files).map(file=>({file,companyId:/^0?[1-6](?=[\s_-])/.exec(file.name)?.[0].padStart(2,'0')||'',taxMode:'confirmar',emptyConfirmed:declared(/^0?[1-6](?=[\s_-])/.exec(file.name)?.[0].padStart(2,'0')||''),replace:false})));setPreviews([]);}
 function update(i:number,c:Partial<UploadRow>){setUploads(uploads.map((u,j)=>j===i?{...u,...c}:u));setPreviews([]);}
 function form(){const f=new FormData();uploads.forEach(u=>f.append('files',u.file));f.append('mapping',JSON.stringify(uploads.map(({file,...u})=>({...u,period}))));return f;}
 return <>{data.demo&&<div className="notice"><CircleHelp size={19}/>A demonstração é somente leitura. Use “Acessar ambiente real” para importar seus arquivos.</div>}<div className="stepper"><span className="current"><b>1</b>Selecionar relatórios</span><ChevronRight size={17}/><span><b>2</b>Validar e importar</span><ChevronRight size={17}/><span><b>3</b>Processar competência</span></div><section className="panel"><div className="panel-heading"><div><h2>Relatórios de ICMS · Consinco</h2><p>Fonte principal: ApuIcms, TXT ou CSV, separado por ponto e vírgula.</p></div><Badge>Até 6 arquivos</Badge></div><button disabled={data.demo||busy} className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!data.demo)choose(e.dataTransfer.files);}} onClick={()=>fileInput.current?.click()}><span className="upload-symbol"><UploadCloud size={29}/></span><b>Arraste os relatórios das empresas</b><span>ou clique para selecionar todos de uma vez</span><small>TXT / CSV · até 3,5 MB por lote · originais preservados</small></button><input ref={fileInput} hidden multiple type="file" accept=".txt,.csv" onChange={e=>choose(e.target.files)}/>
 {uploads.length>6&&<p className="form-error">Selecione no máximo seis arquivos por lote.</p>}
 {uploads.length>0&&<div className="upload-list">{uploads.map((u,i)=><div className="upload-item" key={u.file.name+i}><div className="upload-file"><FileText size={22}/><div><b>{u.file.name}</b><small>{(u.file.size/1024).toFixed(1)} KB · competência {period}</small></div></div><div className="upload-controls"><label>Empresa<select value={u.companyId} onChange={e=>update(i,{companyId:e.target.value,emptyConfirmed:declared(e.target.value)})}><option value="">Confirmar empresa</option>{data.companies.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select></label><label>Mapeamento do ICMS<select value={u.taxMode} onChange={e=>update(i,{taxMode:e.target.value as TaxMode})}><option value="confirmar">Automático pelo cabeçalho</option><option value="por-direcao">Confirmo: entradas = crédito; saídas = débito</option></select></label></div><div className="upload-checks"><label className="check-label"><input type="checkbox" checked={u.emptyConfirmed} onChange={e=>update(i,{emptyConfirmed:e.target.checked})}/>Confirmo sem movimento, se só houver cabeçalho</label><label className="check-label"><input type="checkbox" checked={u.replace} onChange={e=>update(i,{replace:e.target.checked})}/>Substituir importação ativa, preservando histórico</label></div>{previews[i]&&<div className={'preview-result '+(previews[i].error?'invalid':'')}><b>{previews[i].error?'Validação bloqueada':previews[i].rows+' linhas válidas · '+previews[i].encoding}</b>{previews[i].error?<p>{previews[i].error}</p>:previews[i].warnings?.map(w=><p key={w}>{w}</p>)}</div>}</div>)}<div className="form-actions"><button className="button secondary" disabled={busy||uploads.some(u=>!u.companyId)||uploads.length>6} onClick={()=>perform(async()=>setPreviews(await request('preview',form())))}><Search size={16}/>Validar arquivos</button><button className="button primary" disabled={busy||uploads.length>6||previews.length!==uploads.length||previews.some(p=>p.error)||uploads.some(u=>!u.companyId)} onClick={()=>perform(async()=>{await request('import',form());await refresh();setUploads([]);setPreviews([]);notify('Arquivos importados. Clique em Processar competência para atualizar as análises.');})}><Database size={16}/>Importar no banco</button></div></div>}
 <div className="panel-note"><CircleHelp size={15}/>Imposto Creditado é reconhecido nas entradas e Imposto Debitado nas saídas. Quando o cabeçalho divergir, confirme o mapeamento explicitamente.</div><div className="panel-note"><CircleHelp size={15}/>LivroApu e OperInterUF são complementares e não entram nesta soma. Não importe fontes sobrepostas.</div></section><section className="panel"><div className="panel-heading"><div><h2>Cobertura da competência</h2><p>Declare ausência de movimento somente nesta competência. O histórico registra responsável e motivo.</p></div><Badge tone={covered===6?'green':'amber'}>{covered} de 6 empresas</Badge></div><div className="coverage-grid">{data.companies.map(c=>{const i=data.imports.find(i=>i.companyId===c.id),d=data.declarations?.find(d=>d.companyId===c.id);return <article key={c.id}><span className={'coverage-icon '+(i||d?'done':'')}><Building2 size={21}/></span><h3>{c.name}</h3><p>{d?'Sem movimento em '+period:i?i.rowCount+' linhas importadas':'Aguardando relatório'}</p><Badge tone={i||d?'green':'neutral'}>{d?'Sem movimento declarado':i?(i.rowCount?'Importado':'Sem movimento confirmado'):'Pendente'}</Badge>{i&&<small>{i.filename}</small>}{d&&<small>{d.reason} · {new Date(d.declaredAt).toLocaleDateString('pt-BR')}</small>}{!data.demo&&(!i?.rowCount||d)&&<button className="button secondary" disabled={busy} onClick={()=>setDeclaration({companyId:c.id,noMovement:!d})}>{d?'Reabrir movimento':'Declarar sem movimento'}</button>}</article>;})}</div></section><section className="panel"><div className="panel-heading"><div><h2>Layout detalhado opcional</h2><p>Colunas adicionais: Chave NF-e, Documento, Empresa contraparte e Data.</p></div><a className="button secondary" href="/modelo-detalhado.csv" download><Download size={16}/>Modelo fictício</a></div><div className="panel-note">Novos relatórios detalhados devem ser validados com uma amostra do Consinco. Os valores, o sentido do imposto e a rastreabilidade permanecem obrigatórios.</div></section>{declaration&&<Dialog title={declaration.noMovement?'Declarar ausência de movimento':'Reabrir movimento'} onClose={()=>setDeclaration(null)}><form className="form" onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');perform(async()=>{await request('period-status',{...declaration,period,reason});await refresh();setDeclaration(null);notify('Situação atualizada para '+period+'. Reprocesse a competência.');});}}><p>{data.companies.find(c=>c.id===declaration.companyId)?.name} · {period}</p><label>Motivo<textarea required name="reason" minLength={10} maxLength={1000}/></label><button className="button primary" disabled={busy}>Salvar situação da competência</button></form></Dialog>}</>;
}
