'use client';
import {useState} from 'react';
import {BookOpen,History,Search,UploadCloud,Plus,Trash2} from 'lucide-react';
import {FACTS,type FactField,type TaxRule,type TaxRuleInput,type TaxFinding} from '@/lib/tax-motor';
import {Badge,Dialog,Empty,request,type ViewProps} from './ui';
const statuses={pendente:'Pendente de validação',validada:'Validada pela equipe',inativa:'Inativa'};
const fields=Object.entries(FACTS) as [FactField,(typeof FACTS)[FactField]][];
function editable(r:TaxRule):TaxRuleInput {
 const {id,version,title,domain,status,start,end,reference,reason,conditions,requiredFields,checks}=r;
 return {id,version,title,domain,status,start,end,reference,reason,conditions,requiredFields,checks};
}
function RuleEditor({rule,busy,save}:{rule:TaxRule;busy:boolean;save:(r:TaxRuleInput)=>void}){
 const [r,setR]=useState(()=>editable(rule));
 const field=<K extends keyof TaxRuleInput>(key:K,value:TaxRuleInput[K])=>setR({...r,[key]:value});
 return <form className="form" onSubmit={e=>{e.preventDefault();save(r);}}>
  <div className="notice small">O conteúdo recebido é uma referência. Para ativar uma verificação de ICMS, a equipe deve completar e validar as condições, a vigência e o fundamento.</div>
  <label>Título<input required maxLength={250} value={r.title} onChange={e=>field('title',e.target.value)}/></label>
  <div className="form-grid">
   <label>Módulo<select value={r.domain} onChange={e=>setR({...r,domain:e.target.value as TaxRuleInput['domain'],status:'pendente'})}>{['ICMS','PIS/COFINS','IBS/CBS','Procedimento'].map(d=><option key={d}>{d}</option>)}</select></label>
   <label>Situação<select value={r.status} onChange={e=>field('status',e.target.value as TaxRuleInput['status'])}>{Object.entries(statuses).map(([id,label])=><option key={id} value={id} disabled={id==='validada'&&r.domain!=='ICMS'}>{label}</option>)}</select></label>
   <label>Vigência inicial<input type="date" value={r.start} onChange={e=>field('start',e.target.value)} required={r.status==='validada'}/></label>
   <label>Vigência final<input type="date" value={r.end} onChange={e=>field('end',e.target.value)}/></label>
  </div>
  <label>Fundamento validado<textarea maxLength={2000} value={r.reference} onChange={e=>field('reference',e.target.value)} placeholder="Norma, dispositivo e fonte consultada"/></label>
  <label>Justificativa e condições legais<textarea maxLength={3000} value={r.reason} onChange={e=>field('reason',e.target.value)} placeholder="Explique por que esta regra se aplica e quais exceções foram verificadas."/></label>
  <div className="motor-section-title"><h3>Quando aplicar</h3><button type="button" className="button secondary" disabled={r.conditions.length>=20} onClick={()=>field('conditions',[...r.conditions,{field:'cfop',operator:'in',values:['']}])}><Plus size={15}/>Condição</button></div>
  <p className="muted small-text">Todas as condições devem ser atendidas. Dentro de uma lista de códigos, basta um valor. Separe os valores por ponto e vírgula. Campo ausente na origem gera Revisar.</p>
  {r.conditions.map((c,i)=><div className="motor-condition" key={i}>
   <label>Campo<select value={c.field} onChange={e=>field('conditions',r.conditions.map((x,j)=>i===j?{...x,field:e.target.value as FactField,operator:'in'}:x))}>{fields.filter(([,f])=>!f.numeric).map(([id,f])=><option key={id} value={id}>{f.label}</option>)}</select></label>
   <label>Critério<select value={c.operator} onChange={e=>field('conditions',r.conditions.map((x,j)=>i===j?{...x,operator:e.target.value as typeof c.operator}:x))}><option value="in">Está na lista</option>{c.field==='productDescription'&&<><option value="containsAll">Contém todas as expressões</option><option value="excludes">Não contém as expressões</option></>}</select></label>
   <label>Valores<input required value={c.values.join(';')} onChange={e=>field('conditions',r.conditions.map((x,j)=>i===j?{...x,values:e.target.value.split(';')}:x))} placeholder="Ex.: 1102;2102"/></label>
   <button type="button" className="icon-button" aria-label={'Remover condição '+(i+1)} onClick={()=>field('conditions',r.conditions.filter((_,j)=>i!==j))}><Trash2 size={17}/></button>
  </div>)}
  <details className="motor-source"><summary>Campos adicionais obrigatórios ({r.requiredFields.length})</summary><div className="motor-required">{fields.map(([id,f])=><label className="check-label" key={id}><input type="checkbox" checked={r.requiredFields.includes(id)} onChange={e=>field('requiredFields',e.target.checked?[...r.requiredFields,id]:r.requiredFields.filter(v=>v!==id))}/>{f.label}</label>)}</div></details>
  <div className="motor-section-title"><h3>O que conferir</h3><button type="button" className="button secondary" disabled={r.checks.length>=10} onClick={()=>field('checks',[...r.checks,{field:'icmsRate',operator:'equals',values:[''],severity:'media',message:''}])}><Plus size={15}/>Verificação</button></div>
  <p className="muted small-text">Cadastre o valor esperado e a explicação da divergência. Números usam ponto decimal; faixas usam mínimo;máximo. Crédito e débito continuam sendo os valores informados na origem.</p>
  {r.checks.map((c,i)=>{const update=(change:Partial<typeof c>)=>field('checks',r.checks.map((x,j)=>i===j?{...x,...change}:x));return <fieldset className="motor-check" key={i}><legend>Verificação {i+1}</legend><div className="motor-condition">
   <label>Campo<select value={c.field} onChange={e=>{const f=e.target.value as FactField;update({field:f,operator:FACTS[f].numeric?'equals':'in',values:['']});}}>{fields.map(([id,f])=><option key={id} value={id}>{f.label}</option>)}</select></label>
   <label>Comparação<select value={c.operator} onChange={e=>update({operator:e.target.value as typeof c.operator,values:['']})}>{FACTS[c.field].numeric?<><option value="equals">Igual a</option><option value="between">Entre (inclusive)</option></>:<option value="in">Está na lista</option>}</select></label>
   <label>Esperado<input required value={c.values.join(';')} onChange={e=>update({values:e.target.value.split(';')})} placeholder={c.operator==='between'?'mínimo;máximo':'Valor validado'}/></label>
   <button type="button" className="icon-button" aria-label={'Remover verificação '+(i+1)} onClick={()=>field('checks',r.checks.filter((_,j)=>i!==j))}><Trash2 size={17}/></button>
  </div><label>Prioridade da divergência<select value={c.severity} onChange={e=>update({severity:e.target.value as typeof c.severity})}><option value="alta">Alta</option><option value="media">Média</option><option value="baixa">Baixa</option></select></label><label>Explicação do alerta<textarea required minLength={10} maxLength={1000} value={c.message} onChange={e=>update({message:e.target.value})} placeholder="O que divergiu e o que a equipe precisa verificar?"/></label></fieldset>;})}
  <details className="motor-source"><summary>Conteúdo original recebido</summary><p>{rule.sourcePath}</p><pre>{JSON.stringify(rule.source,null,2)}</pre></details>
  <p className="muted small-text">Salvar cria uma nova versão. Resultados já processados mantêm os critérios anteriores. Reprocesse a competência para aplicar a alteração.</p>
  <button className="button primary" disabled={busy}>{busy?'Salvando…':'Salvar nova versão'}</button>
 </form>;
}
export function TaxMotor(props:ViewProps){
 const {data,busy,perform,refresh,notify}=props;
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[domain,setDomain]=useState('all'),[page,setPage]=useState(0);
 const [edit,setEdit]=useState<TaxRule|null>(null),[error,setError]=useState(''),[history,setHistory]=useState<TaxRule[]|null>(null);
 const rules=data.taxRules||[],packages=data.taxPackages||[];
 const filtered=rules.filter(r=>(status==='all'||r.status===status)&&(domain==='all'||r.domain===domain)&&[r.title,r.reference,JSON.stringify(r.source)].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages-1);
 return <section className="panel motor-panel"><div className="panel-heading"><div><div className="eyebrow">BASE TRIBUTÁRIA VERSIONADA</div><h2><BookOpen size={21}/> Motor tributário</h2><p>Referências recebidas, critérios configuráveis e verificações de ICMS.</p></div><label className={'button secondary motor-upload '+(busy||data.demo?'disabled':'')}><UploadCloud size={16}/>Importar pacote JSON<input aria-label="Importar pacote do motor tributário" disabled={busy||data.demo} type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value='';if(!file)return;perform(async()=>{if(file.size>256000)throw new Error('Limite de 256 KB por pacote JSON.');const form=new FormData();form.set('file',file);const result=await request('tax-package',form);await refresh();notify(result.duplicate?'Este pacote já foi importado. Nenhuma regra foi duplicada.':result.package.ruleCount+' referências importadas, pendentes de validação.');});}}/></label></div>
 <div className="motor-stats"><div><strong>{rules.length}</strong><span>Referências recebidas</span></div><div><strong>{rules.filter(r=>r.status==='validada').length}</strong><span>Verificações validadas</span></div><div><strong>{rules.filter(r=>r.status==='pendente').length}</strong><span>Aguardando validação</span></div></div>
 <p className="notice small">Referências históricas não são ativadas na importação. A classificação por CFOP continua no cadastro abaixo; este motor acrescenta verificações por mercadoria e operação. PIS/COFINS, IBS/CBS e roteiros SPED ficam como referências para as próximas fases.</p>
 {!!packages.length&&<details className="motor-source"><summary>Pacotes e arquivos preservados ({packages.length})</summary>{packages.map(p=><article key={p.id}><b>{p.name} · {p.version}</b><p>{p.ruleCount} referências · {new Date(p.importedAt).toLocaleString('pt-BR')}</p><small className="hash">SHA-256: {p.hash}</small><a className="button text-button" href={'/api/tax-source?id='+p.id}>Baixar JSON original</a></article>)}</details>}
 {!!rules.length?<><div className="motor-filters"><label><span><Search size={15}/> Buscar referência</span><input value={query} placeholder="Produto, norma ou NCM do conteúdo original" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><label>Situação<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">Todas</option>{Object.entries(statuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Módulo<select value={domain} onChange={e=>{setDomain(e.target.value);setPage(0);}}><option value="all">Todos</option>{['ICMS','PIS/COFINS','IBS/CBS','Procedimento'].map(d=><option key={d}>{d}</option>)}</select></label></div><div className="motor-list">{filtered.slice(current*12,current*12+12).map(r=><article key={r.id}><div className="motor-record-heading"><div><Badge>{r.domain}</Badge><Badge tone={r.status==='validada'?'green':r.status==='pendente'?'amber':'neutral'}>{statuses[r.status]}</Badge><span className="muted small-text">v{r.version}</span></div><div><button className="icon-button" disabled={busy||data.demo} aria-label={'Histórico de '+r.title} onClick={()=>perform(async()=>setHistory(await request('tax-history?id='+r.id)))}><History size={18}/></button><button className="button secondary" disabled={busy||data.demo} onClick={()=>{setError('');setEdit(r);}}>Revisar critérios</button></div></div><h3>{r.title}</h3><p>{r.reference||'Fundamento específico ainda não cadastrado'}</p><small>{r.start?'Vigência: '+r.start+(r.end?' até '+r.end:' em diante'):'Vigência pendente'} · {r.conditions.length} condições · {r.checks.length} verificações</small><details className="motor-source"><summary>Ver referência recebida</summary><pre>{JSON.stringify(r.source,null,2)}</pre></details></article>)}</div><div className="motor-pagination"><span>{filtered.length} referências · página {current+1} de {pages}</span><button className="button secondary" disabled={current===0} onClick={()=>setPage(current-1)}>Anterior</button><button className="button secondary" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Próxima</button></div></>:<Empty title={data.demo?'Motor disponível no ambiente real':'Importe sua base tributária'}>Envie o JSON do motor. O original será preservado no banco e as referências ficarão disponíveis para configurar as verificações.</Empty>}
 {edit&&<Dialog title="Revisar referência tributária" wide onClose={()=>setEdit(null)}><RuleEditor rule={edit} busy={busy} save={r=>perform(async()=>{setError('');try{await request('tax-rule',r);await refresh();setEdit(null);notify('Nova versão salva. Reprocesse a competência para atualizar os resultados.');}catch(e){setError((e as Error).message);throw e;}})}/>{error&&<p className="form-error" role="alert">{error}</p>}</Dialog>}
 {history&&<Dialog title="Histórico do critério tributário" wide onClose={()=>setHistory(null)}><div className="history-list">{history.map(r=><article key={r.version}><b>Versão {r.version} · {statuses[r.status]}</b><p>{new Date(r.updatedAt).toLocaleString('pt-BR')} · {r.updatedBy}</p><p>{r.reference||'Fundamento pendente'}</p><p>{r.reason||'Justificativa pendente'}</p><details className="motor-source"><summary>Condições e verificações desta versão</summary><pre>{JSON.stringify(editable(r),null,2)}</pre></details></article>)}</div></Dialog>}
 </section>;
}
export function TaxEvidence({findings}:{findings?:TaxFinding[]}){
 if(!findings?.length)return null;
 return <section className="motor-evidence"><h3>Verificações do motor tributário</h3>{findings.map(f=><article key={f.ruleId}><h4>{f.title} · v{f.version}</h4><Badge tone={f.status==='OK'?'green':f.status==='DIVERGENTE'?'red':'amber'}>{f.status==='DIVERGENTE'?'Divergência':f.status==='REVISAR'?'Revisar':'Critério atendido'}</Badge><p>{f.reason}</p><dl>{Object.entries(f.evidence).map(([key,value])=><div key={key}><dt>{FACTS[key as FactField].label}</dt><dd>{value}</dd></div>)}</dl><small>Origem do critério: {f.sourcePath} · versão {f.version}</small></article>)}</section>;
}
