import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const origin='http://127.0.0.1:3000';
const denied=await fetch(origin+'/api/data?period=2026-08');
assert.equal(denied.status,401);
const demo=await fetch(origin+'/api/data?mode=demo&period=2026-08').then(r=>r.json());
assert.equal(demo.demo,true);assert.equal(demo.companies.length,6);
const access=await readFile('ACESSO-LOCAL.txt','utf8');
const password=/Senha: (.+)/.exec(access)[1].trim();
const wrongOrigin=await fetch(origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',origin:'https://example.com'},body:JSON.stringify({email:'admin@megag.local',password})});
assert.equal(wrongOrigin.status,403);
const logged=await fetch(origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify({email:'admin@megag.local',password})});
assert.equal(logged.status,200,await logged.clone().text());
const cookie=logged.headers.get('set-cookie').split(';')[0];
assert.match(logged.headers.get('set-cookie'),/HttpOnly/);assert.match(logged.headers.get('set-cookie'),/SameSite=Strict/);
const real=await fetch(origin+'/api/data?period=2026-08',{headers:{cookie}}).then(r=>r.json());
assert.equal(real.demo,false);assert.equal(real.imports.length,0);assert.equal(real.rules.length,0);assert.equal(real.snapshot,null);
const xlsx=await fetch(origin+'/api/export?mode=demo&period=2026-08&company=all');
assert.equal(xlsx.status,200);const bytes=Buffer.from(await xlsx.arrayBuffer());assert.equal(bytes.subarray(0,2).toString(),'PK');
await mkdir('.data/qa',{recursive:true});await writeFile('.data/qa/DEMO-export.xlsx',bytes);
const report=await fetch(origin+'/api/report?mode=demo&period=2026-08&company=all').then(r=>r.text());
assert.ok(report.includes('DADOS FICTÍCIOS'));assert.ok(report.includes('CFOP'));
const badPeriod=await fetch(origin+'/api/data?mode=demo&period=2026-99');assert.equal(badPeriod.status,400);
const ended=await fetch(origin+'/api/logout',{method:'POST',headers:{cookie,origin,'Content-Type':'application/json'},body:'{}'});assert.equal(ended.status,200);
assert.equal((await fetch(origin+'/api/data?period=2026-08',{headers:{cookie}})).status,401);
console.log('HTTP: acesso restrito, CSRF, sessão, separação demo/real, Excel, relatório e logout verificados.');
